services:
    kafka:
      image: apache/kafka
      ports:
        - 8500:8500
      restart: unless-stopped
      env_file: config/kafka.env
      volumes:
        - ./data/kafka/logs:/var/log/kafka
        - ./data/kafka/secrets:/etc/kafka/secrets:ro
      networks:
        - test-net

networks:
  test-net:
    name: jobs_system_network
    external: true
