services:
    kafka:
      container_name: kafka
      image: apache/kafka
      ports:
        - 8000:8000
        - 8500:8500
        - 9000:9000
      restart: unless-stopped
      user: 1000:1000
      env_file: config/kafka.env
      networks:
        - kafka
      volumes:
        # Kafka cannot work well with NTFS, so be sure that ./ is not on NTFS filesystem
        - ./data/kafka/data:/var/lib/kafka/data
        - ./data/kafka/logs:/var/log/kafka
        - ./data/kafka/secrets:/etc/kafka/secrets:ro

    # Only for debugging
    kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui
      restart: unless-stopped
      user: 6060:6060
      depends_on:
        - kafka
      environment:
        DYNAMIC_CONFIG_ENABLED: true
      ports:
        - 7000:8080
      networks:
        - kafka
      volumes:
      - ./data/kafka-ui/config.yaml:/etc/kafkaui/dynamic_config.yaml
      - ./data/kafka-ui/secrets:/etc/kafkaui/secrets:ro

networks:
  kafka:
    name: kafka
    driver: bridge
