@startuml Create Job

title Создание задачи

boundary "Web API Задач" as API
database "БД Задач" as DB
queue "Очередь Задач" as KAFKA

[-> API: Запрос создания задачи
API -> API: Проверка данных задачи

alt Данные задачи корректны

    API -> DB: Добавление задачи
    API -> KAFKA: Отправка номера задачи
    API ->[: Ответ создания задачи

else Данные некорректны

    API ->[: Ошибка "плохой запрос"

end

@enduml

@startuml Get Job result

title Запрос результатов задачи

boundary "Web API Задач" as API
database "БД Задач" as DB

[-> API: Запрос результатов задачи
API -> DB: Запрос задачи

alt Задача найдена

    DB -> API: Результат задачи
    API ->[: Ответ результата задачи

else Задача не найдена

    DB -> API: Пустой ответ
    API ->[: Ошибка "не найдено"

end

@enduml

@startuml Lost Jobs worker

title Обработка "потерянных" задач

control "Обработчик 'потерянных' задач" as WORKER
database "БД Задач" as DB

== Инициализация ==

WORKER -> WORKER: Запуск цикла обработки

== Обработка потерянных задач ==

loop До запроса завершения

    WORKER -> DB: Пометка задач "потерянными"
    note right
        Задача считается потерянной, если не была
        завершена в течение заданного времени
    end note

    WORKER -> WORKER: Ожидаение следующей итерации

end

== Завершение ==

WORKER -> WORKER: Завершение цикла обработки

@enduml
