@startuml Create Job

title Создание задачи

boundary "Web API Задач" as API
database "БД Задач" as DB
queue "Очередь Задач" as KAFKA

[-> API++: Запрос создания задачи
API -> API: Проверка данных задачи

alt #LightGreen Данные задачи корректны

    API -> DB++: Добавление задачи
    DB --> API--: Возврат
    API -> KAFKA++: Отправка номера задачи
    KAFKA --> API--: Возврат
    API -->[: Ответ создания задачи

else #Pink Данные некорректны

    API -->[--: Ошибка "плохой запрос"

end

@enduml

@startuml Get Job result

title Запрос результатов задачи

boundary "Web API Задач" as API
database "БД Задач" as DB

[-> API++: Запрос результатов задачи
API -> DB++: Запрос задачи

alt #LightGreen Задача найдена

    DB --> API: Результат задачи
    API -->[: Ответ результата задачи

else #Pink Задача не найдена

    DB --> API--: Пустой ответ
    API -->[--: Ошибка "не найдено"

end

@enduml

@startuml Lost Jobs worker

title Обработка "потерянных" задач

control "Обработчик 'потерянных' задач" as WORKER
database "БД Задач" as DB

== Инициализация ==

WORKER -> WORKER++: Запуск цикла обработки

== Обработка потерянных задач ==

loop #LightGray До запроса завершения

    WORKER --> WORKER++: Старт итерации

    WORKER -> DB++: Пометка задач "потерянными"
    note right
        Задача считается потерянной, если не была
        завершена в течение заданного времени
    end note
    DB --> WORKER--: Возврат

    WORKER -> WORKER--: Конец итерации и ожидаение следующей итерации

end

== Завершение ==

WORKER -> WORKER--: Завершение цикла обработки

@enduml
