@startuml Worker loop

title Обработка задач

control "Обработчик задач" as WORKER
control "Анализатор окружения" as ENV
control "Исполнитель задач" as RUNNER
queue "Очередь задач" as KAFKA
database "БД Задач" as DB

== Инициализация ==

WORKER -> KAFKA: Подпись на очередь задач
WORKER -> WORKER: Запуск цикла обработки

== Обработка задач ==

loop До запроса завершения

WORKER -> ENV: Проверка возможности запуска задачи

alt Запуск невозможен

    WORKER -> WORKER: Конец итерации

else Запуск возможен

    WORKER -> KAFKA: Ожидание сообщения о новой задачи
    KAFKA -> WORKER: Ответ номера новой задачи
    WORKER -> DB: Запрос данных новой задачи

    alt Задача существует и не была запущена ранее

        DB -> WORKER: Данные новой задачи
        WORKER -> RUNNER: Запуск задачи
        WORKER -> DB: Пометка задачи, как запущенной

    else Задача не существует или была запущена ранее

        DB -> WORKER: Пустой ответ
        WORKER -> WORKER: Пропуск запуска задачи

    end

    WORKER -> KAFKA: Пометка сообщения, как обработанного

end

    WORKER -> WORKER: Ожидание следующей итерации

end

== Завершение ==

WORKER -> WORKER: Остановка цикла обработки
WORKER -> KAFKA: Отписка от очереди задач
WORKER -> RUNNER: Ожидание завершения уже запущенных задач

@enduml

@startuml Job runner

title Исполнение задач

control "Запуск задач" as STARTER
control "Исполнение задач" as RUNNER
database "БД Задач" as DB

[-> STARTER: Запрос исполнения задачи
STARTER -> STARTER: Проверка, что задача уже запущена

alt Задач уже запущена

    STARTER -> STARTER: Пропуск запуска

else Новая задача

    STARTER -> RUNNER ++: Запуск задачи
    STARTER -> STARTER: Сохранение задачи в список запущенных задач

    RUNNER -> RUNNER: Подготовка окружения
    RUNNER -> RUNNER: Запуск процесса задачи и ожидание его завершения

    alt Процесс завершен успешно

        RUNNER -> RUNNER: Сбор результатов задачи
        RUNNER -> DB: Сохранение результатов задачи и пометка ее, как завершенной
        note right: Результатом может быть "успех" или "таймаут"

    else Процесс завершен с ошибками

        RUNNER -> DB: Пометка задачи, как проваленной

    end

    RUNNER -> RUNNER: Очистка окружения задачи
    RUNNER -> STARTER --: Удаление задачи из списка запущенных задач

end

@enduml
