@startuml User sign up

title Регистрация пользователя

actor Пользователь as USER
boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB

USER -> UI++: Запрос страницы авторизации
UI --> USER: Возврат страницы авторизации
USER -> UI: Ввод авторизационных данных
USER -> UI: Нажатие кнопки "Login"
UI -> API++: Запрос входа
API -> DB++: Запрос пользователя
DB --> API--: Пустой ответ
API -> DB++: Добавление нового пользователя
DB --> API--: Возврат
API --> UI--: Возврат авторизационной куки
UI --> USER: Главная страница веб-приложения

@enduml

@startuml User sign in

title Авторизация пользвателя

actor Пользователь as USER
boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB

USER -> UI++: Запрос страницы авторизации
UI --> USER: Возврат страницы авторизации
USER -> UI: Ввод авторизационных данных
USER -> UI: Нажатие кнопки "Login"
UI -> API++: Запрос входа
API -> DB++: Запрос пользователя
DB --> API--: Ответ пользователя
API -> API: Проверка авторизационных данных

alt #LightGreen Авторизационных данные корректны

    API --> UI: Возврат авторизационной куки
    UI --> USER: Главная страница веб-приложения

else #Pink Авторизационных данные некорректны

    API --> UI--: Отказ доступа
    UI --> USER: Отображение ошибки

end

@enduml

@startuml User job creation

title Создание задачи

actor Пользователь as USER
note over USER: Считаем, что пользователь успешно авторизован

boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB
boundary "Jobs.WebApi" as JOBS

USER -> UI++: Запрос страницы создания задачи
UI --> USER: Страница создания задачи
USER -> UI: Ввод данных задачи
USER -> UI: Нажатие кнопки "Create"
UI -> API++: Запрос создания задачи
API -> API: Проверка данных задачи

alt #LightGreen Данные задачи корректны

    API -> JOBS++: Запрос создания задачи

    alt #LightGreen Задача создана успешно

        JOBS --> API: Ответ номера задачи
        API -> DB++: Добавление задачи
        DB --> API--: Возврат
        API --> UI: Ответ создания задачи
        UI --> USER: Переход на главную страницу

    else #Pink Ошибка создания

        JOBS --> API--: Ошибка создания
        API --> UI: Ошибка создания
        UI --> USER: Отображение ошибки

    end

else #Pink Данные задачи некорректны

    API -> UI--: Ошибка "плохой запрос"
    UI -> USER: Отображение ошибки

end

@enduml

@startuml User jobs list

title Запрос списка задач

actor Пользователь as USER
note over USER: Считаем, что пользователь успешно авторизован

boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB

USER -> UI++: Запрос главной страницы
UI -> API++: Запрос списка задач пользователя
API -> DB++: Запрос списка задач пользователя
DB -> API--: Ответ списка задач пользователя
API --> UI--: Ответ списка задач пользователя
UI --> USER: Главная страница со списком задач пользователя

@enduml

@startuml User job

title Запрос результатов задачи

actor Пользователь as USER
note over USER: Считаем, что пользователь успешно авторизован

boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB
boundary "Web API Задач" as JOBS

USER -> UI++: Запрос страницы результатов задачи
UI -> API++: Запрос результатов задачи
API -> DB++: Запрос задачи
DB --> API--: Ответ задачи
API -> API: Проверка принадлежности задачи пользователю

alt #Pink Задача не принадлежит пользователю

    API --> UI: Ошибка "не найдено"
    UI --> USER: Отображение ошибки

else #LightGreen Задача принадлежит пользователю

    API -> JOBS++: Запрос результатов задачи

    alt #LightGreen Положительный ответ

        JOBS --> API: Ответ результатов задачи
        API --> UI: Ответ результатов задачи
        UI --> USER: Страница результатов задачи

    else #Pink Ошибка "не найдено"

        JOBS --> API--: Ошибка "не найдено"
        API --> UI--: Ошибка "не найдено"
        UI --> USER: Отображение ошибки

    end

end

@enduml
