@startuml User sign up

title Регистрация пользователя

actor Пользователь as USER
boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB

USER -> UI: Ввод авторизационных данных
USER -> UI: Нажатие кнопки "Login"
UI -> API: Запрос входа
API -> DB: Запрос пользователя
DB -> API: Пустой ответ
API -> DB: Добавление нового пользователя
API -> UI: Возврат авторизационной куки
UI -> USER: Главная страница веб-приложения

@enduml

@startuml User sign in

title Авторизация пользвателя

actor Пользователь as USER
boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB

USER -> UI: Ввод авторизационных данных
USER -> UI: Нажатие кнопки "Login"
UI -> API: Запрос входа
API -> DB: Запрос пользователя
DB -> API: Ответ пользователя
API -> API: Проверка авторизационных данных

alt Авторизационных данные корректны

    API -> UI: Возврат авторизационной куки
    UI -> USER: Главная страница веб-приложения

else Авторизационных данные некорректны

    API -> UI: Отказ доступа
    UI -> USER: Отображение ошибки

end

@enduml

@startuml User job creation

title Создание задачи

actor Пользователь as USER
note over USER: Считаем, что пользователь успешно авторизован

boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB
boundary "Jobs.WebApi" as JOBS

USER -> UI: Страница создания задачи
USER -> UI: Ввод данных задачи
USER -> UI: Нажатие кнопки "Create"
UI -> API: Запрос создания задачи
API -> API: Проверка данных задачи

alt Данные задачи корректны

    API -> JOBS: Запрос создания задачи

    alt Задача создана успешно

        JOBS -> API: Ответ номера задачи
        API -> DB: Добавление задачи
        API -> UI: Ответ создания задачи
        UI -> USER: Переход на главную страницу

    else Ошибка создания

        JOBS -> API: Ошибка создания
        API -> UI: Ошибка создания
        UI -> USER: Отображение ошибки

    end

else Данные задачи некорректны

    API -> USER: Ошибка "плохой запрос"
    USER -> API: Отображение ошибки

end

@enduml

@startuml User jobs list

title Запрос списка задач

actor Пользователь as USER
note over USER: Считаем, что пользователь успешно авторизован

boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB

USER -> UI: Главная страница
UI -> API: Запрос списка задач пользователя
API -> DB: Запрос списка задач пользователя
DB -> API: Ответ списка задач пользователя
API -> UI: Ответ списка задач пользователя
UI -> USER: Отображение списка задач пользователя

@enduml

@startuml User job

title Запрос результатов задачи

actor Пользователь as USER
note over USER: Считаем, что пользователь успешно авторизован

boundary "Web UI Пользвателя" as UI
control "Web API Пользвателя" as API
database "БД Пользователей" as DB
boundary "Web API Задач" as JOBS

USER -> UI: Страница задачи
UI -> API: Запрос результатов задачи
API -> DB: Запрос задачи
DB -> API: Ответ задачи
API -> API: Проверка принадлежности задачи пользователю

alt Задача не принадлежит пользователю

    API -> UI: Ошибка "не найдено"
    UI -> USER: Отображение ошибки

else Задача принадлежит пользователю

    API -> JOBS: Запрос результатов задачи

    alt Положительный ответ

        JOBS -> API: Ответ результатов задачи
        API -> UI: Ответ результатов задачи
        UI -> USER: Отображение результатов задачи

    else Ошибка "не найдено"

        JOBS -> API: Ошибка "не найдено"
        API -> UI: Ошибка "не найдено"
        UI -> USER: Отображение ошибки

    end

end

@enduml
