@startuml Create Job

title Создание задачи

start

:Данные новой Задачи<

if (Данные корректны?) then (да)
    :Сгенерировать номер новой Задачи]
    :Добавить новую Задачу в БД Задач|
    :Добавить номер новой Задачи в Очередь Задач]
    :Номер новой Задачи>
else (нет)
    :Ошибка "плохой запрос">
endif

end

@enduml

@startuml Get Job result

title Запрос результатов задачи

start

:Номер Задачи<
:Запрос результатов Задачи из БД Задач|
if (Ответ пустой?) then (да)
    :Результаты задачи>
else (нет)
    :Ошибка "не найдено">
endif

end

@enduml

@startuml Lost Jobs worker

title Обработка "потерянных" задач

start

while (Запрос завершения?) is (нет)
:Пометка задач "потерянными" в БД Задач|

backward :Ожидание следующей итерации
в течение заданного времени]

endwhile (да)

end

@enduml
