@startuml p_jobs_add_new

title Добавление новой Задачи

start

:Данные новой Задачи<
    note right: Номер, время исполнения, скрипт

if (Задача существует?) then (да)
    :Ошибка "Задача существует">
else (нет)
    :Добавить новую Задачу в таблицу Задач]
    note right
        В дополнение к переданным данным: время создания
        Задачи становится равным текущему времени
    end note
endif

end

@enduml

@startuml f_jobs_get_results

title Запрос результатов Задачи

start

:Номер Задачи<
if (Задача существует?) then (да)
    :Результаты Задачи>
    note left: Статус, времена запуска и завершения, артефакты
else (нет)
    :Пустой ответ>
endif

end

@enduml

@startuml f_jobs_set_lost

title Пометка Задач "потерянными"

start

:Временной интервал<
:Пометка Задач, не завершенных в течение заданного
временного интервала, "потерянными"]

end

@enduml

@startuml f_jobs_get_new

title Запрос данных новой Задачи

start

:Номер Задачи<
if (Задача существует и новая?) then (да)
    note left: "Новая" - имеет статус "New"
    :Данные Задачи>
    note left: Номер, время исполнения, скрипт
else (нет)
    :Пустой ответ>
endif

end

@enduml

@startuml p_jobs_set_running

title Пометка Задачи, как запущенной

start

:Номер Задачи<
if (Задача существует?) then (нет)
    :Ошибка "задача не найдена">
    end
else (да)
endif

if (Задача уже запущена?) then (да)
    end
else (нет)
endif

if (Задача уже завершена?) then (да)
    :Ошибка "задача завершена">
    end
else (нет)
endif

:Пометка задачи, как запущенной]
    note right
        Статус становится равным "Running", а время
        запуска становится равным текущему времени
    end note

end

@enduml

@startuml p_jobs_set_results

title Уставновка результатов Задачи

start

:Номер Задачи<
:Статус Задачи<
:Артефакт Задачи<

if (Статус не соответсвует завершенному состоянию) then (да)
    :Ошибка "неверный статус">
        note left: "Завершенный статус" - это: "Finished", "Timeout", "Fault", "Lost"
    end
else (нет)
endif

if (Задача существует?) then (нет)
    :Ошибка "задача не найдена">
    end
else (да)
endif

if (Задача уже завершена?) then (да)
    :Ошибка "задача завершена">
    end
else (нет)
endif

:Запись результатов задачи]
    note right
        Статус становится равным переданному, а время
        завершения становится равным текущему времени
    end note

end

@enduml
