@startuml Worker loop

title Обработка задач

start

:Подпись на Очередь Задач]

while (Запрос завершения?) is (нет)

:Анализ возможности запуска задач|
if (Запуск возможен?) then (да)

    :Запрос номера новой Задачи из Очереди Задач]
    :Запрос данных новой Задачи из БД Задач|

    if (Задача существует и не была запущена ранее?) then (да)
        :Запуск новой Задачи|
        :Пометка Задачи, как запущенной, в БД Задач|
    else (нет)
    endif

else (нет)
endif

:Пометка Задачи, как обработанной, в Очереди Задач]

backward :Ожидание следующей итерации
в течение заданного времени]

endwhile (да)

:Отписка от Очереди Задач]
:Ожидание завершения уже запущенных Задач]

end

@enduml

@startuml Resource analyzer

title Анализ возможности запуска задач

start

if (Число уже запущенных задач больше 16?) then (да)
    :Отрицательный ответ>
    end
else (нет)
endif

if (Нагрузка на процессор больше 80%?) then (да)
    note left
        Нагрузка на процессор определяется на основе
        использования процессорного времени из файла /proc/stat
        Для определения нагрузки, из файла дважды, с заданным
        временным промежутком, считывается общее процессорное
        время и время простоя
    end note
    :Отрицательный ответ>
    end
else (нет)
endif

if (Занятость памяти больше 80%?) then (да)
    note left
        Занятость памяти определяется на основе данных из
        файла /proc/meminfo
        Из файла считываются показатели общего объема памяти
        и доступного объема памяти
    end note
    :Отрицательный ответ>
    end
else (нет)
endif

if (Использованного места на диске больше 80%?) then (да)
    :Отрицательный ответ>
    end
else (нет)
endif

:Положительный ответ>

end

@enduml

@startuml Job runner

title Исполнение Задачи

:Данные новой Задачи<
if (Задача уже запущена?) then (да)
    end
else (нет)
endif

:Добавить задачу в список уже запущенных задач]
:Подготовка окружения Задачи|
:Запуск исполнения Задачи в контейнере|
if (Контейнер завершился с ошибками?) then (да)
    :Пометка Задачи, как проваленной в БД Задач|
else (нет)
    :Сбор артефактов Задачи|
    if (Задача исполнялась дольше заданного времени?) then (да)
        :Сохранение артефактов Задачи в БД Задач
        с результатом "Таймаут"|
    else (нет)
        :Сохранение артефактов Задачи в БД Задач
        с результатом "Успешно"|
    endif
endif

:Очистка окружения задачи|
:Удаление задачи из списка уже запущенных Задач]

end

@enduml

@startuml Create environment

title Подготовка окружения Задачи

:Данные Задачи<

if (Данные Задачи корректны?) then (да)
    :Создать директорию Задачи]
    :Создать файл stdout.txt c правами u+rw,o+w]
    :Создать файл stderr.txt c правами u+rw,o+w]
    :Записать скрипт Задачи в файл run.sh c правами u+rw,o+r]
    :Путь к директории Задачи>
else (нет)
    :Ошибка целостности Задачи<
endif

end

@enduml

@startuml Clean environment

title Очистка окружения задачи

:Данные Задачи<

if (Данные Задачи корректны?) then (да)
    :Удалить директорию Задачи]
else (нет)
    :Ошибка целостности Задачи<
endif

end

@enduml

@startuml Docker

title Запуск исполнения Задачи в контейнере

:Данные Задачи<

if (Данные Задачи корректны?) then (да)
    :Создать контейнер]
    :Запустить контейнер]
    :Ожидание завершения контейнера]
    :Остановить контейнер]
    :Удалить контейнер]
    :Результат завершения контейнера>
else (нет)
    :Ошибка целостности Задачи>
endif

end

@enduml

@startuml Results collector

title Сбор артефактов Задачи

:Данные Задачи<

if (Данные Задачи корректны?) then (да)
    :Создать ZIP-архив из файлов stdout.txt и stderr.txt из окружения Задачи]
    :ZIP-архив>
else (нет)
    :Ошибка целостности Задачи>
endif

end

@enduml
