@startuml SslValidator

start

:Сертификат для проверки<

if (Сертификат подписан доверенным корневым сертификатом?) then (нет)
    :Ошибка "недоверенный сертификат">
    end
else (да)
endif

if (Сертификат отозван?) then (да)
    :Ошибка "сертификат отозван">
    end
else (нет)
endif

if (Срок действия сертификата истек?) then (да)
    :Ошибка "истек срок действия сертификата">
    end
else (нет)
endif

:Проверка успешна>

end

@enduml
