@startuml User sign up/in algorithm (WebAPI)

title Авторизация пользователя

start

:Авторизационные данные<

if (Данные корректны?) then (нет)
    :Ошибка "плохой запрос">
    end
else (да)
endif

:Запрос числа неудачных попыток авторизации
из списка заблокированных пользователей]

if (Число попыток больше или равно 5?) then (да)
    :Ошибка "отказ в доступе">
    end
else (нет)
endif

:Запросить данные пользователя из БД Пользователей|
if (Ответ пустой?) then (да)
    :Сгенерировать соль]
    :Посчитать хеш пароля пользователя со сгенерированной солью]
    :Добавить пользовтеля в БД Пользователей|
else (нет)
    :Посчитать хеш пароля пользователя с солью,
    полученной из БД Пользователей]
    if (Посчитанный хеш и хеш из БД совпадают?) then (да)
        :Сбросить число неудачных попыток авторизации
        в списке заблокированных пользователей]
    else (нет)
        :Инкрементировать число неудачных попыток авторизации
        в списке заблокированных пользователей]
        :Ошибка "отказ в доступе">
        end
    endif
endif

:Авторизационная кука>
:Перенаправить пользователя на главную страницу]
end

@enduml

@startuml Job creation

title Создание новой Задачи

start

:Данные новой Задачи<

if (Данные корректны?) then (да)
    :Добавить новую Задачу в API Задач|
        note left: С возвратом номера созданной Задачи
    :Сохранить Задачу в БД пользователей|
    :Ответ "создано">
else (нет)
    :Ошибка "плохой запрос">
endif

end

@enduml

@startuml Jobs list

title Запрос списка Задач

start

:Запрос Задач пользователя из БД Пользователей|
:Список Задач>

end

@enduml

@startuml Job results

title Запрос результатов Задачи

start

:Номер Задачи<
:Проверить существование и принадлежность
Задачи пользователю в БД Пользователей|

if (Результат проверки положительный?) then (да)
    :Запросить результаты из API Задач|
    :Результаты Задачи>
else (нет)
    :Ошибка "не найдено">
endif

end

@enduml
