@startuml p_users_add_new_user

title Добавление нового пользователя

start

:Данные пользователя<
    note right: Имя, Хеш пароля, Соль
if (Пользователь существует) then (да)
    :Ошибка "пользователь существует"<
else (нет)
    :Добавить пользователя в таблицу пользователей]
endif

end

@enduml

@startuml f_users_get_user

title Запрос данных пользователя

start

:Имя пользователя<

if (Пользователь существует) then (да)
    :Данные пользователя<
        note left: Имя, Хеш пароля, Соль
else (нет)
    :Пустой ответ<
endif

end

@enduml

@startuml p_users_add_new_job

title Добавление новой Задачи

start

:Имя пользователя<
:Номер Задачи<

if (Пользователь существует) then (да)
    if (Задача существует) then (да)
        :Ошибка "Задача существует">
    else (нет)
        :Добавление Задачи в таблицу Задач]
    endif
else (нет)
    :Ошибка "пользователь не существует">
endif

end

@enduml

@startuml f_users_get_user_jobs

title Запрос Задач пользователя

start

:Имя пользователя<

if (Пользователь существует) then (да)
    :Список Задач пользователя>
else (нет)
    :Пустой ответ>
endif

end

@enduml

@startuml f_users_check_user_job

title Проверка принадлежности Задачи пользователю

start

:Имя пользователя<
:Номер Задачи<

if (Пользователь существует) then (да)
    if (Задача существует и принадлежит пользователю) then (да)
        :Положительный ответ>
        note left
            Задача принадлежит пользователю, если в таблице
            Задач есть запись, связывающая номер Задачи
            с именем пользователя
        end note
        end
    else (нет)
    endif
else (нет)
endif

:Отрицательный ответ>

end

@enduml
